validation: sovereign
version: 1
accounts:
    - name: alice
      coins:
        - 2000000000umars
      mnemonic: __RELAYER_MNEMONIC__
    - name: bob
      coins:
        - 100000000umars
faucet:
    name: bob
    coins:
        - 100000umars
    port: 4501
default_denom: umars
validators:
    - name: alice
      bonded: 100000000umars
      app:
        api:
            enable: true
            swagger: true
            address: tcp://0.0.0.0:1317
            max-open-connections: "1000"
        grpc:
            address: 0.0.0.0:9091
            enable: true
      config:
        p2p:
            laddr: tcp://0.0.0.0:26656
        rpc:
            laddr: tcp://0.0.0.0:26657
